language: java
services: docker

before_script:
  - env | sort
  - repo="arpitjindal1997/telegram-aircel-bot"
  - image="$repo:latest"
  - heroku_repo="registry.heroku.com/infinite-scrubland-51571/web:latest"

script:
  - mvn clean package
  - docker build -t $image .

after_script:
  - docker images
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $repo
  - docker login --username=_ --password="$heroku_auth_token" registry.heroku.com
  - docker tag $image $heroku_repo
  - docker push $heroku_repo 
